//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public long Id { get; set; }
        public int OrderId { get; set; }
        public int BookId { get; set; }
        public int Count { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual OrderHeader OrderHeader { get; set; }
    }
}
